# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.4.x
      - name: Run tests
        run: |
          uv run pytest tests/ -v
        env:
          UV_PYTHON: '${{ matrix.python-version }}'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.4.x
      - name: Lint with ruff
        run: |
          uvx ruff check .
      - name: Check formatting with black
        run: |
          uvx black --check .
